POST https://hng-task-2-production-d672.up.railway.app
Content-Type: application/json

{
  "firstName": "Presh",
  "lastName": "Emmanuel",
  "email": "precious.enuagwune@eng.uniben.edu",
  "password": "JohnBull2",
  "phone": "09038383838"
}


###

POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "email": "preciousifeaka@gmail.com",
  "password": "Ifakaye"
}

###

GET http://localhost:8001/api/users/a363472b-1c0e-4fcf-8b19-b93ad3452145
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHJlY2lvdXNzZWVtbWFudWVsQGdtYWlsLmNvbSIsImlhdCI6MTcyMDI4MDY3M30.cd_721xMc8YJKobihy4ehhCC19PhZ_1SVp6Od_gIO1w

###

GET https://hng-task-2-production-d672.up.railway.app/api/organisations

